<?php

namespace AppBundle\Repository;

/**
 * DayNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayNameRepository extends \Doctrine\ORM\EntityRepository
{
}
