<?php

namespace AppBundle\Repository;

/**
 * RecipePlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipePlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function groupByDay($id)
    {
        return $this->createQueryBuilder('rp')
            ->where('rp.plan= :id')
            ->setParameter('id', $id)
            ->groupBy('rp.dayName')
            ->getQuery()
            ->getResult();
    }
}
