<?php

namespace AppBundle\Repository;

/**
 * RecipesIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipesIngredientsRepository extends \Doctrine\ORM\EntityRepository
{
}
