<?php

namespace AppBundle\Repository;

/**
 * RecipePlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipePlanRepository extends \Doctrine\ORM\EntityRepository
{
}
